feat(RSS): add refresh all rss feeds button to rss articles
VueTorrent/VueTorrent pull request #1679
Opened 2024-05-08 15:27 UTC by aforty

# feat: add 'refresh all rss feeds' button to rss articles page

Addresses #1586. Simply adds a new `refreshAllFeeds()` to the rss store, complete with toast notification. Only thing missing are other translations, it only pulls from `en` right now.

First time using vue, it's very possible I messed up something obvious.

## PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All tests pass
- [x] I've removed all commented code

2024-05-08 17:23 UTC, Larsluph requested changes
Thanks for the contribution!
I was in the process of reworking the whole UI to merge the feeds and rules view into this one, you got faster than me!

2024-05-08 17:23 UTC, Larsluph commented on src/pages/RssArticles.vue
> +              <v-btn :disabled="rssStore.feeds.length === 0" :text="$t('rssArticles.refreshAllFeeds')" color="primary" @click="rssStore.refreshAllFeeds()" />
Don't use HTML character entities.
I would wrap both buttons in a flex div with a gap of 8px instead.
Moreover this makes the responsive design completely messed up, so you could add a flex-column with the `$vuetify.display.mobile` prop.

```suggestion
              <div :class="{'d-flex gap': true, 'flex-column': $vuetify.display.mobile}">
                <v-btn :disabled="rssStore.unreadArticles.length === 0" :text="$t('rssArticles.markAllAsRead')" color="primary" @click="rssStore.markAllAsRead()" />
                <v-btn :disabled="rssStore.feeds.length === 0" :text="$t('rssArticles.refreshAllFeeds')" color="primary" @click="rssStore.refreshAllFeeds()" />
              </div>
```

And add the class in the component:

```css
.gap {
  gap: 8px;
}
```

2024-05-08 17:47 UTC, aforty commented
Thanks for the tip. Fixed!

2024-05-09 10:23 UTC, WDaan approved these changes

2024-05-09 10:24 UTC, merged

2024-05-09 10:24 UTC, WDaan commented
Thanks for contributing! 😃 

Great addition